packages:
  - 'packages/*'
  - 'apps/frontend/payroll'
  - 'apps/frontend/employee'
  - 'libs/frontend-lib'
  - 'apps/backend/*'
  - 'apps/frontend/host'
  - 'apps/frontend/host-app'
  - 'apps/frontend/simple'
